### ISSUE TITLE
Support encoded polyline as request parameters

### ISSUE THREAD

**Issue by kofronpi** [Skalar/google_distance_matrix#20]
It would be great if the `google_distance_matrix` would support encoded polylines as request parameters, which allow to query for more locations in a single API call:

https://developers.google.com/maps/documentation/distance-matrix/intro#RequestParameters

**Comment by thhermansen** [comment]
I agree that would be great. Feel free to see if you can implement it and submit a pull request. Remember to write rspec tests for your submitted code.

I think a good way to do it is to have one class handle the conversion between lat/lng to encoded polylines. Then let [`Place#to_param`](https://github.com/Skalar/google_distance_matrix/blob/master/lib/google_distance_matrix/place.rb#L31-L34) use that class to return it's lat/lng values encoded instead of lat/lng numeric value.

`Place#to_param` already receives `options` from [`UrlBuilder#params`](https://github.com/Skalar/google_distance_matrix/blob/master/lib/google_distance_matrix/url_builder.rb#L51-L56) and the `UrlBuilder` has access to the configuration object so we can add one option to the config to let users either use encoded values or the old lat/lng values like we have it today.

**Comment by kofronpi** [comment]
@thhermansen Would you advise leveraging an existing gem as a dependency to encode/decode polylines such as https://github.com/joshuaclayton/polylines or not ?

I'll have a look to see if I can free some time to submit a PR.

**Comment by thhermansen** [comment]
I took this one as a Monday challenge and think I have something which works. Please take a look at #24.

Please try it out and see if it works as expected and let me know how it goes as a comment in that pull request :)
