### ISSUE TITLE
Add US unit support

### ISSUE THREAD

**Issue by caseyprovost** [Skalar/google_distance_matrix#40]
Distance should be able to be returned in standard or metric units

**Comment by thhermansen** [comment]
Hi,

It's been a bit of a time since I worked on this gem, so I may be remembering wrong, but are what you are looking for maybe [this configuration option](https://github.com/Skalar/google_distance_matrix/blob/master/lib/google_distance_matrix/configuration.rb#L26)?

See [README](https://github.com/Skalar/google_distance_matrix#configuration) for how to set configurations. It can also be done like [this](https://github.com/Skalar/google_distance_matrix#do-some-configuration---see-googledistancematrixconfigure_defaults-as-well).
